services:
  - type: web
    name: alpro-supabase-cloud
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PUBLIC_URL
        sync: false
